repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.5.1"
    hooks:
      - id: mypy
        additional_dependencies:
          - aiovantage==0.13.0b2
          - voluptuous-stubs==0.1.1
          - homeassistant-stubs==2023.9.3
        args: []

  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        args: ["--github", "--notitle", "--maxlevel=2", "--update-only"]
