---
name: "Feature request"
description: "Suggest an idea for this project"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "Before you open a new feature request, search through the existing feature requests to see if others have had the same idea."

  - type: textarea
    attributes:
      label: "Describe the problem"
      description: "A clear and concise description of what the problem is."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
          required: true
        - label: This issue is not a duplicate of [previous feature requests](https://github.com/loopj/home-assistant-vantage/issues?q=label%3Aenhancement).
          required: true
